"2. View Expenses\n",
"3. Search Expenses\n",
"4. Edit Expenses\n",
"5. Delete Expenses\n",
"6. Monthly Summary\n",
"7. Category Summary\n",
"8. Highest Expense\n",
"9. Lowest Expense\n",
"10.Exit\n",